### ISSUE TITLE
Define the Frontend for Demonstrating WAX Functionality

### ISSUE THREAD

**Issue by voltrevo** [getwax/wax#12]
We need a UI for demonstrating all the things we're building.

This issue is just about planning. Let's consider it done when we have a solid outline for what we want to do and have new issues that lay the path forward.

**Comment by voltrevo** [comment]
I propose that we start with an in-page wallet.
- The in-page wallet is a library that implements `window.ethereum` and is backed by a smart account with wax functionality
- By default, the in-page wallet behaves like a secure extension-based wallet
- This allows existing dApps that target generic web3 to get a plug-n-play experience
- dApps can then opt-in to customization to deliver simplified experiences:
  - store the keyphrase on the user's behalf, and bypass the normal wallet onboarding
  - change the popup behavior for approving wallet functions, replacing it with a similar component that can be embedded in the dApp or bypassing approval entirely
  - control which network the wallet is connected to

An additional benefit of defaulting to the appearance of a secure extension-based wallet is it eases the transition to a secure wallet. This is for both:
1. The user - they get the same familiar experience after the transition
2. The WAX team - in future we can make an extension variation with mostly the same code

In the default UI, we should include some messaging about upgrading the security of their account.

I'd also like to suggest that this project include the ability to deploy all the related contracts. Let's not have multiple moving parts. Instead, a dev can start up this project without anything else (let's even include `hardhat node` (or similar) by default) and the wallet detects the contracts aren't deployed and simply guides the dev through that part of the process.

Finally, let's pay attention to the design of the UI. First and foremost, it should feel like a bit of a blank slate - a starting point for developers to build into a real product. At the same time though, it should have some polish - some kind of balance between bland and slick - perhaps monochrome(ish) by default, but also with pleasant spacing and a good starting point for how the UX is broken down into screens and how those screens are laid out. This should be constrained by keeping the code as simple as possible - minimize dependencies and assumptions, and make the code feel like it comes from a beginners' book.

**Comment by voltrevo** [comment]
Let's support multiple ways of using this:
- Import an npm module
- Fork the repo and use the builtin dev server / example dApp
- Copy the library into an existing project (similar to module but makes it easier to customize)
  - Need to consider licensing here - either advice about separating the MIT license, or it might be worth using CC0/unlicense to ease the friction of being a template
- Publicly hosted instance(s)

Personas:
- Experienced developer with existing established dApp
  - Likely to import a module and configure it to an existing network
- Beginner
  - Likely to use the repo directly with the built-in `hardhat node` and start building on an example
- Experienced developer without existing dApp
  - Might use any of these options, but needs less guidance
- Non-developer (or otherwise) who just wants to see concrete versions of our stuff
  - Likely to use publicly hosted deployments of example dApps
  - (Or in future - see third party dApps/wallets that have integrated WAX component(s))

**Comment by voltrevo** [comment]
We should include at least one minimal dApp (eg for using [Greeter](https://sepolia.etherscan.io/address/0xf02ce35c9d9a5c3ae1e4aeeef0f624bc11ed10f4#code)) demonstrating integration of the library. This is what developers will see when they start the project.

**Comment by JohnGuilding** [comment]
I like the general idea of this. 

### Thoughts on having a single dApp

I know the idea of creating a dedicated example dApp for **each "WAX feature/module"** has been thrown around. I think I prefer this approach for the following reasons:
- We don't have to update multiple repos when we release new code or need to make a small change like updating an rpc endpoint (something we had to do with WAX V1).
- From the perspective of the personas you've outlined, being able to see what functionality WAX offers in a single location is easier from a UX standoint, as opposed to spinning up 3 dapps to see all of our features.

If we went for this approach, we would want a intuitive UX for showing how a user can interact with the different features of WAX. E.g. If I just want to learn about/try out the zkemail feature, then I should be able to do that, and not get bogged down with information about BLS vs EOA, and webauthn all at once. Maybe on wallet creation, the user could choose what features they want? And then have the option to add/remove different modules/plugins at their discretion?

### Thoughts on "in-page wallet"

In terms of what sort of UI we build and the in-page wallet idea, I'm in favour of doing something like this too. Thoughts on this are:
- Committing to building an extension straight away would be be unnecessarily complex/time-consuming.
- Building "just a instant wallet" feels like we are ignoring the fact that most users and developers use and build extension wallets.
- Making our code easy to implement in a browser environment and an extension environment feels like it delivers the most value. So this approach seems to satisfy that point.
- Agree with the UI being a blank slate but also slightly polished

**Questions**:
1. In terms of implementation (as I don't know much about building an extension), how much less complex do you think building the "in-page wallet" will be, compared to an actual secure extension?
2. "defaulting to the appearance of a secure extension-based wallet" - in terms of appearance are you suggesting that the UI is 1) more like a dapp with the "extension" that pops up in the top right? Or 2) more like the Quill homepage and then some "dApp" UI next to it? Or 3) something else?
3. " in future we can make an extension variation with mostly the same code" - how much code could we actually reuse, as I understand we wouldn't be able to replicate a lot of things that extensions give you?

### other points
> I'd also like to suggest that this project include the ability to deploy all the related contracts.

+1

> minimize dependencies and assumptions, and make the code feel like it comes from a beginners' book.

+1

> We should include at least one minimal dApp (eg for using Greeter) demonstrating integration of the library.

+1. Perhaps even something that replicates using a real product, like swapping a token?

**Comment by blakecduncan** [comment]
I like it, these are good ideas.  I agree with pretty much everything you are saying.  Before going into too much detail on the specifics, I just want to make sure I’m tracking everything.  You are proposing we do the following:

**In-page wallet**
- Library that copies the `window.ethereum` interface
A dApp dev should be able to do `const provider = new ethers.providers.Web3Provider(window.ethereum);` but with our `window.ethereum` object

- This library would also include frontend code.  For example, when a dApp dev calls `eth_requestAccounts`, our in-page wallet will display a pop-up.  This popup will mock an actual extension wallet.
We may want to think through how a dApp could do some of the things you mentioned.  For example, storing the key phrase themselves.  I’m just trying to think through how the dev would interact with the library.

**dApp that uses the above in page wallet**

**Additionally: all of our contracts live here for easy deployment**

Is this understanding right?

If so, I have one main question - where would the code live that enables different verification methods for the smart account?  For example, if the end-user wanted to validate a transaction with webAuthN, would that code live in the in-page wallet? Or would that code be implemented as a separate node module that the dApp initializes and passes the wallet? Or something else? 

Finally, I wouldn’t be opposed to deviating from traditional extension wallet UX if that was the intention.

**Comment by voltrevo** [comment]
I don't have time to respond fully yet, but I should clarify that the smart contracts would not live inside this subproject. They'd be imported in instead.

I'll follow up properly when I get some time.

Cheers for the feedback :)

**Comment by voltrevo** [comment]
@JohnGuilding

> Thoughts on having a single dApp

I wouldn't describe it that way (but I think the points you made still stand). It's more of a common baseline. The in-page wallet should be independent of the dApp that uses it, so a wax feature could have a specialized dApp to better demonstrate itself if needed. But yeah if `Greeter` is sufficient then features could just share that one.

> Maybe on wallet creation, the user could choose what features they want? And then have the option to add/remove different modules/plugins at their discretion?

Possibly yeah, something to figure out as we go.

> In terms of implementation (as I don't know much about building an extension), how much less complex do you think building the "in-page wallet" will be, compared to an actual secure extension?

I think in the short term it saves a lot of time, but in the longer term it's a small difference.

> "defaulting to the appearance of a secure extension-based wallet" - in terms of appearance are you suggesting that the UI is 1) more like a dapp with the "extension" that pops up in the top right? Or 2) more like the Quill homepage and then some "dApp" UI next to it? Or 3) something else?

More like (1).

> " in future we can make an extension variation with mostly the same code" - how much code could we actually reuse, as I understand we wouldn't be able to replicate a lot of things that extensions give you?

Ideally making an extension variation would be a very small change, (so almost 100% is reused). It depends how we build it though. We just need to keep some abstractions in mind so that we separate the code that's truly in-page (implementing `window.ethereum` over messaging and without access to private keys etc) and the code that does the real crypto stuff and could be run in a secure context. I think that's a helpful distinction to make anyway.

>> We should include at least one minimal dApp (eg for using Greeter) demonstrating integration of the library.
>
> +1. Perhaps even something that replicates using a real product, like swapping a token?

Quite possibly yeah. I mean I'd defer it until we have something minimal working, but I can see how something more realistic like that could increase the appeal. We could potentially have an assortment of an example dApps.

**Comment by voltrevo** [comment]
@blakecduncan

> A dApp dev should be able to do const provider = new ethers.providers.Web3Provider(window.ethereum); but with our window.ethereum object

Yep exactly.

> This library would also include frontend code. For example, when a dApp dev calls eth_requestAccounts, our in-page wallet will display a pop-up. This popup will mock an actual extension wallet.

👍

> If so, I have one main question - where would the code live that enables different verification methods for the smart account? For example, if the end-user wanted to validate a transaction with webAuthN, would that code live in the in-page wallet? Or would that code be implemented as a separate node module that the dApp initializes and passes the wallet? Or something else?

Option 2. I see that code living in its own separate space (probably its own subproject in the wax repo). In general, I think we should avoid getting into a situation where the demo/in-page wallet becomes the source of truth. We don't want people thinking they need to use 'our wallet' in order to use modules. Each module should stand on its own, and we're merely providing an example of its use. Depending on the complexity of the module, this could mean that the module publishes some code (eg on npm) that can be imported into the demo, or the module just describes the code that's needed for integration, and we use that code in the demo.

**Comment by voltrevo** [comment]
This is coming along now with the [protype merged in](https://github.com/getwax/wax/pull/13).

I've added the following issues proposing the path forward:
- https://github.com/getwax/wax/issues/18
- https://github.com/getwax/wax/issues/19
- https://github.com/getwax/wax/issues/20
- https://github.com/getwax/wax/issues/21

**Comment by voltrevo** [comment]
Meeting with @jzaki:
- Education aspect
- Show message about security/upgrading in dialog(s)
- When hosted, get feedback from ethereum wallets discord
