### ISSUE TITLE
Create recovery email verification circuit

### ISSUE THREAD

**Issue by jacque006** [getwax/wax#172]
*As a* Account abstraction developer
*I would like to* Have a ZK circuit which verifies that an email that is requesting recovery is valid
*So I can* Easily write & use the circuit in an account recovery plugin

### Depends on
https://github.com/getwax/wax/issues/170

### Details
https://zkemail.gitbook.io/zk-email/zk-email-verifier

This is a placeholder issue as it is likely the ZKEmail team will help to build this.

- Circuit needs on-chain/EVM runnable verification logic (circom -> snarkjs -> solidity, halo2 -> ? -> solidity)
  - Does not need to adhere to ERC-4337 validation restrictions as it will be run during UserOp/txn execution phase

#### Email contents that need to be checked
See https://github.com/getwax/wax/issues/170

- Email passes expected dkim signing
- Email is from expected recovery linked email account
  - commitment: `hash(fromEmail, salt)`
- New signer to rotate to matches
- What else?

**Comment by Divide-By-0** [comment]
This is SOULs: https://github.com/SoulWallet/email-approver/blob/main/packages/circuits/EmailApprover.circom
