### ISSUE TITLE
Update compression to 4337 contracts v0.7.0

### ISSUE THREAD

**Issue by JohnGuilding** [getwax/wax#226]
Following https://github.com/getwax/wax/pull/224, we have updated the wax `plugins` directory to use 4337 contracts v0.7.0. While the compression e2e tests pass now, the compression contracts and the inpage demo will be broken. The big breaking change is that the UserOperation struct has been changed.

See:
- [PackedUserOperation](https://github.com/eth-infinitism/account-abstraction/blob/develop/contracts/interfaces/PackedUserOperation.sol)
- [UserOperationLib](https://github.com/eth-infinitism/account-abstraction/blob/develop/contracts/core/UserOperationLib.sol)

This issue is concerned with updating the compression compression contracts to use the updated `PackedUserOperation` struct. This will include `HandleOpsCaller` & `HandleAggregatedOpsCaller` since both of those files pull the old `UserOperation` struct. The inpage demo should also be updated.

**Comment by jacque006** [comment]
Closing in favor of https://github.com/getwax/wax/issues/253
